# Setup
title:               Samkit Dayak
tagline:             'Vijay Ramchandra Suri'
description:         'दीक्षायुग प्रवर्तक जैनशासन शिरताज तपागच्छाधिराज परमपूज्य आचार्यदेव श्रीमद् विजय रामचन्द्र सूरीश्वरजी महाराजा।'
url:                 https://sonam09.github.io/samkit-dayak
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sonam Jain
  url:               https://github.com/sonam09
  # email:             

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
#   - jekyll-paginate

locale: 'hi_IN'
webmaster_verifications:
  google: FP67GLZDOceOip6Rr8ZasbtaOiLxmshfAHQvRohevOc
#   bing:

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y

collections_dir: docs
collections:
  section_1:
    output: true
    sort_by: order
  section_2:
    output: true
    sort_by: order